name: CI/CD Pipeline

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Error Message
      run: echo "$ERROR"

    - name: Build and push Docker images
      run: |
        
        docker build -t ml-data-collection-service --label "Simulates weekly sensor data collection and uploads to Google Cloud." -f DatacollectionDockerFile .
        docker build -t ml-data-transfer-service --label "Transfers local data to Google Cloud Storage on a simulated weekly basis." -f DataTransferDockerFile .
        docker build -t ml-model-training-service --label "Configures and runs model training on Google Cloud using uploaded data." -f ModelTrainingDockerFile .
        docker build -t ml-inference-service --label "Evaluate and update the model for local inference if it performs better." -f ModelEvaluationandUpdateDockerFile .

        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        docker tag ml-data-collection-service ${{ secrets.DOCKER_USERNAME }}/ml-data-collection-service
        docker tag ml-data-transfer-service ${{ secrets.DOCKER_USERNAME }}/ml-data-transfer-service
        docker tag ml-model-training-service ${{ secrets.DOCKER_USERNAME }}/ml-model-training-service
        docker tag ml-inference-service ${{ secrets.DOCKER_USERNAME }}/ml-inference-service

        docker push ${{ secrets.DOCKER_USERNAME }}/ml-data-collection-service
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-data-transfer-service
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-model-training-service
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-inference-service