name: CI/CD Pipeline

on:
  push:
    branches:
      - dheeraj

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker-action@v2
      with:
        docker-version: '20.10.8'  # You can adjust the Docker version

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/Trigger:latest -f dockerfiles/TriggerDockerFile .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push {{ secrets.DOCKER_USERNAME }}/Trigger:latest
