name: CI/CD Pipeline

on:
  push:
    branches:
      - none

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t ${DOCKER_USERNAME}/trigger:latest -f dockerfiles/TriggerDockerFile .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push ${DOCKER_USERNAME}/trigger:latest
